apiVersion: v1
kind: Pod
metadata:
  name: termination-demo
  namespace: beyond
spec:
  containers:
  - name: termination-demo-container
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "sleep 10 && echo Sleep expired > /dev/termination-log"]
